<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x86</RuntimeIdentifiers>
    <RootNamespace>CaffeinePro</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>CaffeinePro.App</StartupObject>
    <ApplicationIcon>Resources\Coffee.ico</ApplicationIcon>
    <PackageProjectUrl>https://github.com/fsol11/CaffeinePro</PackageProjectUrl>
    <Copyright>Copyright (c) 2024 Lotrsoft Inc.</Copyright>
    <Description>Keeps Windows awake</Description>
    <PackageIcon>Coffee.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/fsol11/CaffeinePro</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <SignAssembly>False</SignAssembly>
    <Deterministic>false</Deterministic>
    <AssemblyOriginatorKeyFile>E:\dev\SigningCertificate\StrongNamingCertificate\LotrasoftStrongNamingCertificate.snk</AssemblyOriginatorKeyFile>
    <Title>Caffeine Pro</Title>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <FileVersion>
    </FileVersion>
    <Version>2.6.434</Version>
    <DelaySign>False</DelaySign>
    <UseWindowsForms>False</UseWindowsForms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="Notification.Wpf" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="WPF-UI" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Coffee.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Resource>
    <None Remove="Resources\About.mp4" />
    <None Remove="Resources\Coffee16.ico" />
    <Resource Include="Resources\Coffee16.ico" />
    <None Remove="Resources\Coffee32.ico" />
    <Resource Include="Resources\Coffee32.ico" />
    <None Remove="Resources\CoffeeDot.ico" />
    <None Remove="Resources\Software-Install.ico" />
    <Content Include="Resources\Coffee.ico" />
    <EmbeddedResource Include="Resources\About.mp4" />
    <Resource Include="Resources\Software-Install.ico" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Controls\AwakenessViewControl.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="App.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>App.settings</DependentUpon>
    </Compile>
    <Compile Update="Controls\AwakenessViewControl.xaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>AwakenessViewControl.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>